### ISSUE TITLE
Player hit behavior

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#14]
When the player collides with a damaging object:
-emit a "burst" visual effect, e.g. particles shoot out
-player becomes invincible to further damage for 1000 ms
-player sprite flashes or "blinks" in and out rapidly for duration of invincibility

While invincible these visual effects should not occur.

**Comment by perfecthumaninterface** [comment]
While invincible these visual effects should not occur.

**Comment by alkaitagi** [comment]
Implemented

**Comment by perfecthumaninterface** [comment]
There should be a visual effect for the duration of the invincibility. Originally I was thinking the player sprite could blink rapidly but I think what we should do for now is just set the player sprite opacity to 50% during invincibility and return to 100% as soon as it ends.

**Comment by alkaitagi** [comment]
Done.
![image](https://user-images.githubusercontent.com/32439229/58437610-64da6580-80d3-11e9-9681-fd61b27340b2.png)

**Comment by perfecthumaninterface** [comment]
The duration of invincibility value should be exposed so it can be adjusted as necessary.

**Comment by alkaitagi** [comment]
Exposed.

**Comment by perfecthumaninterface** [comment]
Probably the player should not collide with (and therefore destroy) bullets during invincibility.

**Comment by alkaitagi** [comment]
I will building a new modular effect system so that will take some time.

**Comment by alkaitagi** [comment]
Fixed
