### ISSUE TITLE
Player wall collision behavior

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#16]
Currently while "sliding" along walls (and presumably other objects), the player moves more slowly than usual (i.e. moving Right against a wall angled diagonally up and to the right). This should be corrected so the player always moves at full speed (even if they are not inputting that exact direction). In other words the player speed should be normalized.

Additionally, the player should be able to move to the point of collision with diagonal walls. Currently, there is some space between the player collision box and the walls when touching diagonal walls, while there is no space while touching non-diagonal walls.
![image](https://user-images.githubusercontent.com/35180513/54084365-13a5ab80-4306-11e9-951c-226cf206f454.png)

**Comment by perfecthumaninterface** [comment]
I think this is sufficiently addressed. Did you want to comment on it before I close it?

**Comment by alkaitagi** [comment]
Yes, I think reducing the friction of physic materials along with the wall tilemap collider improvements are good enough for now for this to be closed. The issue can be reopened again in the future if needed.
