### ISSUE TITLE
Camera behavior

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#18]
Camera behavior should be modified as such:

-no camera lag (with player movement)

-*during combat mode* camera scrolls a short distance in the direction of the mouse relative to the player (center of the screen). The camera should not tilt.

-*during build mode* the camera stays centered on the player.

**Comment by TiredOfCoding** [comment]
Implemented:
https://github.com/TiredOfCoding/ProjectBurst/releases/tag/v0.1.0-alpha4

**Comment by perfecthumaninterface** [comment]
Camera should follow the mouse equally in all directions. 

Camera mouse following should remain consistent whether in build mode or not.

Camera mouse following behavior should have two parameters, one setting the maximum offset and another setting "sensitivity" or how far you need to move the mouse to hit the maximum.

**Comment by perfecthumaninterface** [comment]
Current implementation seems good, including the parameter ranges, but there is still the issue of it working differently horizontally vs vertically.

The effect is exaggerated if you switch to windowed mode and resize the window to be very thin and wide, indicating that it's tied to screen dimensions. Ideally the offset "limit" would be a circular range from the center point of the screen.

**Comment by alkaitagi** [comment]
Now cursor position is being clamped to a circle with radius equal to the smaller side of the screen (in pixels), which should make offset work properly for non-square screen ratios.

**Comment by perfecthumaninterface** [comment]
I believe this is good now.
