### ISSUE TITLE
Player movement input behavior

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#19]
Currently movement input functions as desired when pressing one or two directional buttons (WASD), but when more than two buttons are pressed the behavior is inconsistent. This should be corrected as such:

When a directional input button is pressed, it will go onto a "stack," which keeps track of the order in which the buttons were pressed. The most recent button press goes onto the top of the stack.

When a button is released, it is removed from the stack (regardless of position in the stack).

The top two buttons (or one if only one exists) in the stack are used to determine movement direction.

**Comment by alkaitagi** [comment]
Implemented: https://github.com/alkaitagi/ProjectBurst/commit/6d63e42f14c0da1ab39985b231722d4c07f0e7a9
