### ISSUE TITLE
Build Menu style

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#20]
Build menu should replace small buttons with large clickable rectangular zones that surround the player, similar to pic: 
![image](https://user-images.githubusercontent.com/35180513/55277699-4f1a1100-52d9-11e9-8b79-c09da3b73d53.png)
The zones should be semi-transparent, and should be clearly labeled. 

In the future I expect these will probably be "categories" that will show more options once clicked on. For now, they can just replace the function of the existing buttons.

**Comment by alkaitagi** [comment]
Implemented: e869f8bc5dc61a13568a35a047610ae871053204

**Comment by perfecthumaninterface** [comment]
There is a small bug where the build circle will return to the scene origin when it shrinks/disappears instead of staying centered at the player position.

**Comment by perfecthumaninterface** [comment]
![image](https://user-images.githubusercontent.com/35180513/55686486-ca11a600-592f-11e9-86a8-0c6d64b7ecdd.png)

This implementation works well, however I'd like the clickable areas to be a bit larger. I chose the orientation in the mockup in the original post because it allows the rectangles to be large without overlapping. There are other shapes/orientations that could fit together well but I figured we would just use the simple rectangles for now.

**Comment by alkaitagi** [comment]
> There is a small bug where the build circle will return to the scene origin when it shrinks/disappears instead of staying centered at the player position.

Fixed that.

**Comment by alkaitagi** [comment]
![image](https://user-images.githubusercontent.com/32439229/55750241-8744f080-5a4b-11e9-825e-39040a31aee9.png)

This is current building selection UI look.

**Comment by perfecthumaninterface** [comment]
Looks good
