### ISSUE TITLE
Add debug info toggle

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#25]
Add a key that will toggle debug info being drawn to screen, including:
-FPS
-display mode (borderless, fullscreen, etc)
-is vsync enabled

And any other info which may be relevant or useful (can be added in the future).

**Comment by alkaitagi** [comment]
Implemented: https://github.com/alkaitagi/ProjectBurst/commit/7371d1048efe5bc9dfe9af1b837d6734916c5d6c

**Comment by perfecthumaninterface** [comment]
We will at some point need to change the key for this since Esc will be needed for pause/menu, so we might as well just change it now.

If ` cannot be used maybe we could use F1. It just needs to be something out of the way that we won't use for other things.

**Comment by alkaitagi** [comment]
Now the panel is being toggled by '`' key.

**Comment by perfecthumaninterface** [comment]
There is a bug with the displayed values not being synchronized with the actual set display mode/vsync. 

-When the game is launched, the set values may be incorrect until you disable/re-enable them.
-When you disable fullscreen and enable it again, it will change to exclusive fullscreen while the dropdown may still say windowed fullscreen (for example).

**Comment by alkaitagi** [comment]
I removed fullscreen toggle, now it is being controlled by the render option:
- exclusive fullscreen (true fullscreen)
- maximized window (borderless fullscreen)
- windowed (just a window)

Also now default values are applied correctly.

**Comment by perfecthumaninterface** [comment]
Currently switching to windowed mode and changing (shrinking) the window size, and then changing to other render modes will cause the game to render blurry/upscaled and at the same screen ratio as the window was set to before changing render modes.

**Comment by alkaitagi** [comment]
Fixed

**Comment by perfecthumaninterface** [comment]
Seems to work.
