### ISSUE TITLE
Building placement partially outside of safe zone

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#27]
Currently 1x3 "wall" buildings can be placed reaching outside of safe zone bounds as long as the center square is inside. All grid spaces of buildings should be within safe zone bounds.

**Comment by alkaitagi** [comment]
Now distance check is being performed for all the points: https://github.com/alkaitagi/ProjectBurst/commit/e01439de20e8ff68836f4d7d47066ebd83f9d1cb

**Comment by perfecthumaninterface** [comment]
Can you explain what was changed? I don't think I noticed a difference in the way it works.

**Comment by alkaitagi** [comment]
Thank you for reporting. In the comment referenced above I have added distance check for each of grid spaces of the building, but missed to implement safe area check for the grid spaces. Now it should work as expected.

**Comment by perfecthumaninterface** [comment]
Currently the game does not take into account rotation of structures in determining valid building placement.

**Comment by alkaitagi** [comment]
Fixed
