### ISSUE TITLE
Player shot/enemy collisions inconsistent

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#28]
For some reason shot collisions around the edges of enemy units/structures seems inconsistent. 

It seems as though sometimes the colliders on enemies are smaller than others.

If there is some way to draw the colliders during gameplay that would probably be helpful for debugging.

**Comment by TiredOfCoding** [comment]
Addressed:
https://github.com/TiredOfCoding/ProjectBurst/releases/tag/v0.1.0-alpha4

**Comment by perfecthumaninterface** [comment]
This unfortunately continues to be an issue. I'm not sure why the "continuous" collision detection in the rigidbody doesn't seem to work, however I feel that using Collider2D.Cast is the best way to go about this. The shot can call the cast per-step and the "distance" argument would determine the distance the shot travels per step. This will make it impossible for the collision to skip over anything and also give us the exact end-point of the shot, which will be useful for more correct visual effect.

I'm also concerned about the previous increase of the physics calculations unnecessarily affecting performance so I'm hoping we can revert that change.

**Comment by alkaitagi** [comment]
Implemented manual sub-frame collider cast for projectiles.

**Comment by perfecthumaninterface** [comment]
Currently the player shots seem to ignore collision until they reach one shot-length away from where they are created, i.e. they will pass through objects if you are close enough to them. The issue is more visible with high bullet speeds. 

![image](https://user-images.githubusercontent.com/35180513/56868319-cddc9980-69be-11e9-8f56-2b01969c9609.png)

**Comment by alkaitagi** [comment]
Fixed by implementing manual simulation, thank you.

**Comment by alkaitagi** [comment]
There is still a problem with bullets not hitting spawners.

**Comment by alkaitagi** [comment]
Fixed by adding kinematic collider to bullets.
