### ISSUE TITLE
Re-enable cursor during building placement 

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#29]
Not being able to see the cursor position during building placement is slightly disorienting so it should be re-enabled.

**Comment by alkaitagi** [comment]
Done

**Comment by perfecthumaninterface** [comment]
Looks good but since reenabling the cursor I've noticed the building placement seems to not line up quite right with the cursor. Especially noticeable when placing a vertical wall and moving the mouse horizontally. This should probably be adjusted/compensated.

**Comment by perfecthumaninterface** [comment]
This issue is completed. Added new issue here: https://github.com/alkaitagi/ProjectBurst/issues/30
