### ISSUE TITLE
Enemy shot range tied to firing distance

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#31]
Currently the behavior of enemies is to move into range of their shot and then attack. Because of this, the distance enemies attack from and the distance the shot travels can't be adjusted independently. 

This should be changed to allow adjusting these things independently.

**Comment by alkaitagi** [comment]
Vision component now has 2 separated fields: detectionRange and attackRange.

**Comment by perfecthumaninterface** [comment]
Currently the Range parameter in Base Launcher seems to be inconsistent during play. If I set this value to 1, sometimes units will shoot what appears to be 1 unit length and sometimes they will shoot significantly further.

**Comment by alkaitagi** [comment]
Is this the correct Creep setup? I cannot reproduce the issue. 
![image](https://user-images.githubusercontent.com/32439229/56893005-ff6e6700-6a89-11e9-92ad-f32d0687782a.png)

**Comment by perfecthumaninterface** [comment]
I believe the original issue has been resolved.
