### ISSUE TITLE
Player shot direction tied to offset rather than player center

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#32]
Currently the shot direction is determined by the cursor position relative to the shot offset (the y value at least) rather than the player origin. So, if I put the cursor between the shot offset position and the player it shoots backwards.

The shot direction should be determined by the position of the cursor relative to the center of the player.

![image](https://user-images.githubusercontent.com/35180513/56868344-362b7b00-69bf-11e9-9ac1-c681057a0d4c.png)

**Comment by alkaitagi** [comment]
Fixed
