### ISSUE TITLE
Building placement at edge of player circle inconsistent with other placement behavior

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#34]
The placement of buildings near the edge of the player generated circle appears to be inconsistent with ground/safe zone areas in that a placement may be invalid even if the center points of the cells are within the player generated circle.

![image](https://user-images.githubusercontent.com/35180513/56868432-590a5f00-69c0-11e9-936a-b31f3617842d.png)

**Comment by alkaitagi** [comment]
Fixed
