### ISSUE TITLE
Player shot visual terminating too soon

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#35]
Currently the player shot is destroyed before the last segment of the visual can be drawn. This looks off and makes it so the range of the player's weapon is not correctly represented.

A suggestion I've been given is to have the trails on a separate object that follows the transform of the bullet objects. Possibly (my assumption) the Autodestruct parameter could be used with this to remove it when appropriate? https://docs.unity3d.com/ScriptReference/TrailRenderer-autodestruct.html

**Comment by alkaitagi** [comment]
Now targetFramerate is set to 300

**Comment by alkaitagi** [comment]
Your suggestion is right. Now Bullets utilize new Detacher component. Also changed trail of CircleBullet to particle emitter.
