### ISSUE TITLE
New launcher type - spread launcher

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#38]
A new launcher type for enemies, which fires multiple bullets at a time in a spread pattern.

Should include the following parameters:
- Number of bullets
- Angle between each bullet (symmetrical)
- Spread between bullet origins (I think this should be arc shaped ideally?)

![image](https://user-images.githubusercontent.com/35180513/58057646-9c756a80-7b33-11e9-813f-38f16dbf3901.png)

**Comment by alkaitagi** [comment]
![image](https://user-images.githubusercontent.com/32439229/58795747-1e6d9500-8604-11e9-8632-4dfdae85669d.png)
