### ISSUE TITLE
Unit and structure hit behavior

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#39]
Unit and structure sprites should flash (solid color) when they take damage.

The flash should be brief (2 frames maybe?), and should occur every time damage is applied, with a minimum time enforced between flashes.

In other words, when the flash occurs a (very) short timer should start, and if the unit takes damage before the timer expires then it won't flash again until the timer ends. Timer length might be something like one or two frames.

**Comment by alkaitagi** [comment]
Added HitFlash component.

**Comment by perfecthumaninterface** [comment]
I think that we should not use WaitForEndOfFrame since it is framerate dependent and instead have a separate duration time that can be set in seconds. We will need to add something that can cause continuous damage in order to test this properly.

**Comment by alkaitagi** [comment]
Agree, added `float pause` property to HitFlash component.

**Comment by perfecthumaninterface** [comment]
Seems perfect now.
