### ISSUE TITLE
Creep Z axis rotation when scene is reset (R)

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#46]
When pressing the R key to reset the scene state, if vsync is disabled, units at the start of the scene will be incorrectly rotated on the z-axis. If vsync is enabled when the R key is pressed, they will return to normal.

**Comment by alkaitagi** [comment]
Fixed. The source of the problem, I believe, was in disabling Agent's rotation on Creep's Start. Apparently, Agent has some short time to update before Creep's Start. Moving the disabling code into Creep's Awake has solved the problem.
