### ISSUE TITLE
Player Respawn

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#47]
When the player dies, wait ~2500 ms and then respawn the player at the player origin.

The player origin should be definable in the scene.

**Comment by alkaitagi** [comment]
Added `PlayerCheckpoint` component with `float Delay` property and Checkpoint object. Player gains a short invincibility upon spawning. As for now, the Checkpoint object does not have `Health` component, and hence cannot be destroyed.
![image](https://user-images.githubusercontent.com/32439229/58439761-8f7deb80-80de-11e9-8c79-0d29a41c9460.png)

**Comment by perfecthumaninterface** [comment]
During the delay after player death, the camera should not return to the checkpoint until afterwards when the player spawns.

**Comment by perfecthumaninterface** [comment]
There seems to be a bug where the respawn does not work at all when I build and run the game, although it appears to work correctly when running in preview.

**Comment by alkaitagi** [comment]
> There seems to be a bug where the respawn does not work at all when I build and run the game, although it appears to work correctly when running in preview.

I am having the same issue plus Checkpoint's radial bar is much wider when running compiled build. Not yet understand how can it be.

**Comment by alkaitagi** [comment]
Camera no longer immediately focuses Checkpoint after Player's death.

**Comment by perfecthumaninterface** [comment]
Would it be possible to make the camera scroll quickly to the checkpoint rather than moving instantaneously? Maybe even use the built-in damping, although it's set very low.

**Comment by alkaitagi** [comment]
Need it explore Cinemachine for that. Sure it is possible.

**Comment by alkaitagi** [comment]
![image](https://user-images.githubusercontent.com/32439229/69003130-e1753080-090d-11ea-9625-b9a0945a401d.png)
Implemented using custom camera blends stored in the **Rendering** folder. Feel free to modify the asset.

**Comment by perfecthumaninterface** [comment]
Currently the camera begins moving to the spawn point at the moment of player death. Ideally it would wait for a time (while the death animation plays), then begin to move to the spawn point.

Best behavior would be that the camera has finished moving to the spawn point before the player is respawned. But I think maybe these timings should just be set manually.

**Comment by perfecthumaninterface** [comment]
There is also a strange camera behavior when respawning at the spawn point at the top of the map. I suspect it may be related to the fact that the camera cannot naturally move to that point during gameplay while the player is alive because of the camera boundaries around the edge of the map.

**Comment by alkaitagi** [comment]
The problem is that the camera confiner extension is applied to the main camera, so when player dies and the respawn camera takes control, the bounding effect is not longer on it. I will think on how to make that extension global.

**Comment by alkaitagi** [comment]
It turned out that camera confining only works with 2d orthographic camera (which makes sense). So I have removed confining and just colored global camera with the same colors as of walls, to disguise the discontinuity.

**Comment by alkaitagi** [comment]
Also implemented camera shake after player's bomb explosion. Wanted to play with that effect.

**Comment by perfecthumaninterface** [comment]
Camera shake is a nice effect. That will be good to use during the player death animation. During gameplay, it should be used with subtlety if at all. The current implementation is excessive but a good experiment. 

The solution removing the camera confiner seems good. I'll just point out that the issue with the camera moving immediately after death instead of waiting for the death animation still persists.

**Comment by alkaitagi** [comment]
Checkpoint now has `CameraDelay`.
![image](https://user-images.githubusercontent.com/32439229/69446101-bef77300-0d64-11ea-9e37-fd4414e47461.png)

**Comment by perfecthumaninterface** [comment]
Increasing the Camera Delay seems to cause the camera to "jump" before reaching the spawn point. The fix appears to be to add the same amount to the Respawn Duration, e.g. if Camera Delay is 1.8 then Respawn Duration should be set to 3.8 (or higher). The camera blend time is set to 2 seconds so 2 seconds + 1 second delay =3 which was the same as the Respawn Duration before editing. I'm guessing once the player object has spawned the camera cancels the transition and switches immediately to follow. 

I think that the Camera Delay value should be added to Respawn Duration internally. That way, the Respawn Duration will control the time after the Camera Delay has finished, and any changes to Camera Delay will keep the rest of the respawn behavior consistent.

**Comment by alkaitagi** [comment]
Right, when Player spawns it takes control over transition making the camera immediately focus it. Implemented internal addition as suggested.

**Comment by alkaitagi** [comment]
Added `CameraTransition` component where you can specify:
- `delay` before start of the transition
- whether to use `global` coordinates for position and rotation
- final `position` camera transform
- final `rotation` of camera transform

Checkpoint now makes use of that component and it internally adds the component's `delay` to its `RespawnDuration`.

![image](https://user-images.githubusercontent.com/32439229/69474749-b12e0600-0dd5-11ea-9d13-6d7ffc678d28.png)

**Comment by alkaitagi** [comment]
Updated *Checkpoint* with non-symmetric progress bar.

![image](https://user-images.githubusercontent.com/32439229/70386159-2f2e0780-19a7-11ea-9c97-0abcbc36d8c5.png)

**Comment by perfecthumaninterface** [comment]
I'm not very worried about the visual effect here right now, but it would make more sense for the progress bar to not start filling up until the camera reaches the checkpoint. I think it would make sense to fully separate the different blocks of time we're working with when the player dies. First there is the wait time when the death animation happens, then the time for the camera to transition back to the respawn point, then the actual respawning time should start after that point. Does that make sense?

**Comment by alkaitagi** [comment]
Right, that would be more intuitive; implemented.

**Comment by perfecthumaninterface** [comment]
As far as I can see the behavior of the progress bar seems unchanged.

**Comment by alkaitagi** [comment]
It has changed, it is just still ignoring the actual transition. While in the component we specify a value for delay, the actual delay is that delay + blend duration. So we need to decide what to do with the blend duration, subtract it either from camera transition delay, or from player respawn duration.

**Comment by alkaitagi** [comment]
Implemented using subtraction of blend time from total delay.

**Comment by perfecthumaninterface** [comment]
Currently with a Delay value of 2 in the Camera Transition script, there doesn't appear to be any delay before the transition begins. With a value of 3, there appears to be about 1 second of delay.

Also, would it be simple to add another parameter that would allow the respawn countdown to begin a little earlier (or later) than the moment the camera transition ends?

**Comment by alkaitagi** [comment]
This behavior is totally expected, as we have camera blend time 2 sec., so 2-2=0 i.e. no delay.

**Comment by perfecthumaninterface** [comment]
Ok, so this works as-is, but it is a bit confusing. I don't want to waste time making everything "just so." Functional is good enough.

That said, this seems like it's more complicated or maybe just more counterintuitive than it needs to be. I can't really follow what you're doing behind the scenes so I apologize for that. But here is how I would structure the actions out mentally:

Player dies > There is a delay time (player watches death animation)
Delay time finishes > begin camera transition, trigger another delay time
Second delay time finishes > begin respawn countdown

Here of course we'd have to take into account the camera blend time, similar to as it is currently, while setting the second delay value, but it seems to me more sensible and it would also allow us to fine-tune exactly when the respawn timer starts (which was my request in the last post). Hopefully that is clear.

I'll ask you whether you agree and what your advice is on whether we should bother to change it or keep it as-is.

**Comment by alkaitagi** [comment]
Thank you. Now _CameraTransition_ has delay (watch death animation) and __PlayerCheckpoint__ has delay (including camera transition) as well.

**Comment by perfecthumaninterface** [comment]
This works exactly as expected, but could you change these names to "Respawn Delay" and "Respawn Duration?"
![image](https://user-images.githubusercontent.com/35180513/71346089-0ffdb100-2535-11ea-8d56-48ea86eb0c15.png)

**Comment by alkaitagi** [comment]
Done.

**Comment by perfecthumaninterface** [comment]
Excellent, let's move on!

**Comment by perfecthumaninterface** [comment]
I've noticed the player has no invincibility period upon respawning. I believe we had this before. But we should put that in place.

**Comment by alkaitagi** [comment]
Fixed.
