### ISSUE TITLE
Player health reduction should be independent of damage

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#49]
Our units and structures and weapons have variable damage, but especially as we add in new things to fight we'll want the player to take only 1 damage for each hit they take (such that getting hit is always consistent no matter the source).

So if we set player health to 5 then they can take 5 hits before they die.

**Comment by alkaitagi** [comment]
Added `DamageType` property to the Health component.
![image](https://user-images.githubusercontent.com/32439229/58473361-11a6f800-8151-11e9-8223-f4fe446226a1.png)

**Comment by perfecthumaninterface** [comment]
This was replaced with the "Normalize Damage" option. I guessed this would cause all damage taken to be 1 but it seems to be something more like .01 . The player takes many hits to be killed with this enabled.

**Comment by perfecthumaninterface** [comment]
Now also the "Is Invincible" setting seems not to work on the player health component.

**Comment by alkaitagi** [comment]
Fixed both and added transparency effect that makes projectiles pass collision.

**Comment by perfecthumaninterface** [comment]
Normalize damage option appears to work as expected.

I'm not certain what "Is Transparent" is intended to do but I don't see it working.
I also don't see the "Is Invincible" option working.

**Comment by xaydaqan** [comment]
I tried to fix them during recent projectile rework, please reevaluate.

**Comment by perfecthumaninterface** [comment]
As far as I can tell these seem fixed. I'm still confused about the necessity of the "value" and "max" parameters for setting health though. It seems like they should always be the same value. If there's a purpose to this though it's not a problem.

**Comment by alkaitagi** [comment]
It is useful for debugging, but gameplay-wise with that we can spawn units (Player) with some capacity in terms of healing.

**Comment by perfecthumaninterface** [comment]
So is "value" the health given at spawn (and the current health during gameplay) and "max" is then the max health? 

Perhaps the names could be improved. Like maybe "Current" instead of "Value."
(I am curious also how hard is it to simply change a variable name? Do you have to make changes throughout the code?)

**Comment by alkaitagi** [comment]
Right, the naming can be improved, which is done trough code.

**Comment by alkaitagi** [comment]
Renamed.
