### ISSUE TITLE
Player basic shot behavior

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#5]
Player's basic shot should be a rapid fire shot that alternates from side to side, as if there are two guns firing alternately. Shots should fly straight with no deviation.

Player's shots should be fairly high velocity (much faster than enemy shots) in addition to shooting rapidly. 

The shots should not be too small (visually and in terms of collision). This will ensure hitting enemies does not require too much precision.

All elements of the shot behavior naturally may need future adjustments,

![image](https://user-images.githubusercontent.com/35180513/53669257-7cc15b00-3c44-11e9-8481-45c08385c734.png)

**Comment by perfecthumaninterface** [comment]
![image](https://user-images.githubusercontent.com/35180513/55691151-fdbcf200-5968-11e9-88ff-99c0f0570387.png)

My thought is that there should be 3 added parameters.

The first two determine the points of origin for the shots, one effecting how far "forward" from the center of the player the shots originate from, and one determining the "width" or the horizontal distance between the shot origins. 

The last one should be a boolean that determines whether or not the shots fire simultaneously or with offset timing (the offset being equal to half of the cooldown time).

**Comment by alkaitagi** [comment]
Now Player uses TLauncher component.
