### ISSUE TITLE
Controls icon during build mode

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#51]
Since the build mode will have some important controls, we should show an icon similar to this in the corner of the screen to make it clear to the player.

![image](https://user-images.githubusercontent.com/35180513/58597858-ddfac980-8247-11e9-95aa-5ca66584825d.png)

There's some possibility that the control functions could change depending on the context, so it would be best to draw the text in-game with the possibility of changing it.

**Comment by alkaitagi** [comment]
![image](https://user-images.githubusercontent.com/32439229/59222536-7000bb80-8bd2-11e9-9ad3-12967ef79a98.png)

**Comment by perfecthumaninterface** [comment]
This should probably remain present while placing buildings in build mode, especially since that's when the snap function will be primarily used.

It's possible the visual could get in the way in rare cases but we could do something like have it fade to transparent when the cursor gets nearby. That's more of a polish detail and can be addressed later.

**Comment by alkaitagi** [comment]
Fixed.

**Comment by perfecthumaninterface** [comment]
I think you may have fixed something but it wasn't what I was originally indicating in my previous post. 

Currently, when you open the build menu the icon shows up, and then when you select a building to press the build menu disappears along with the icon. I think the icon should remain visible at this point, while placing the building. 

![image](https://user-images.githubusercontent.com/35180513/71611427-bb76b900-2b66-11ea-8432-d3940b8c0b07.png)

**Comment by alkaitagi** [comment]
Strange, it is working for me. Please, check again if you are on "Tether" branch.

![image](https://user-images.githubusercontent.com/32439229/71613810-73cd4d00-2bb9-11ea-9353-4044d79f6ee5.png)

**Comment by alkaitagi** [comment]
Fixed. I did not sync BuildManager from Combattest scene.

**Comment by perfecthumaninterface** [comment]
This is a nitpick, perhaps it's slightly distracting, but having this element zoom in and out from the center of the screen like the rest of the build menu seems unnecessary. Could we remove that effect?

**Comment by alkaitagi** [comment]
Fixed (from 0.5 to 1)

![image](https://user-images.githubusercontent.com/32439229/71656873-3cdc7000-2d4e-11ea-8065-6333c676f363.png)
