### ISSUE TITLE
Structure build time

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#52]
When placing structures, there should be a brief building time.

The structure should be placed immediately but not become active until after a building period. During the building period, the structure should not collide with any bullets or attacks. Ideally it would not be targeted by any enemy attacks. But it also should not be able to be moved through and units should path around it. It should block further structures from being placed in the area it occupies. 

In terms of implementation it could be a separate object placed during build time that is immediately swapped out for the real structure once the timer completes. Of course that's only a suggestion.

Visually there should be some kind of animation indicating that the structure is coming into existence. We can focus on making it look good later.

**Comment by alkaitagi** [comment]
Implemented

**Comment by perfecthumaninterface** [comment]
This is working as expected but it could look a lot better. I don't want to spend a lot of time on it but if you could make it so the sprite appears full size but the color changes through a definable gradient as it builds then I think that would be good enough.

**Comment by perfecthumaninterface** [comment]
I'm thinking I'll try to create an animation for this using shaders.

**Comment by alkaitagi** [comment]
BuildGhost is now animated through shader.

**Comment by perfecthumaninterface** [comment]
Indeed. The animation is a bit different, and much simpler (lol). But we can always play with it in the future.
