### ISSUE TITLE
Build mode circle outline

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#54]
Currently entering the build mode shows a solid transparent circle around the player to indicate build range. 

I'd like to try replacing this solid circle with a circle that is only a drawn outline, that is also less transparent.

**Comment by alkaitagi** [comment]
![image](https://user-images.githubusercontent.com/32439229/58708001-2f799480-83bf-11e9-8d12-8f373a0f3611.png)
