### ISSUE TITLE
Grid snap during build mode should be toggle

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#55]
Currently the snap during build mode requires you to hold middle mouse button.

This should be toggled when middle mouse button is pressed instead.

**Comment by alkaitagi** [comment]
Adjusted, now toggle occurs only on mouse button down.

**Comment by perfecthumaninterface** [comment]
The issue seems to have resurfaced

**Comment by alkaitagi** [comment]
Fixed.
