### ISSUE TITLE
Structures with even number diameter should be offset in grid snapping

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#58]
First of all, I don't know whether there would be a reason to define a building to have a diameter that isn't an integer value. I think it would make sense to restrict building diameter to an integer (replacing current "radius").

With this in mind, structures with even number diameters should not snap to the center of grid squares. Their snap should be offset by 0.5 in both axis but still centered under the mouse position.

**Comment by alkaitagi** [comment]
Fixed
