### ISSUE TITLE
AI issues

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#60]
Currently some of the AI seems to have some issues.

In the screenshot below, all the circled units and turrets are doing nothing.
![image](https://user-images.githubusercontent.com/35180513/58601336-5799b400-8256-11e9-96ef-0b5e3cf6622b.png)

I suspect that the turrets are focusing on the spawner but refuse to shoot at it, and the creeps are doing likewise to the turrets.

**Comment by alkaitagi** [comment]
The issue was a result of moving Turret under Building layer. Fixed by adding `detectionMask` property to Vision component where you can explicitly specify on which layers targets can be detected.

**Comment by perfecthumaninterface** [comment]
The behavior does not appear to be any different for me.

**Comment by alkaitagi** [comment]
Right, there is issue with detection since Launcher (who performs aim check) is not aware of Vision's detection mask. I actually will need to refactor relations between classes across the entire unit/building/modules system. Will create another branch for that.

**Comment by alkaitagi** [comment]
So, the unit refactoring has failed, the old logic is reverted, should work now.
