### ISSUE TITLE
Bugs with CircleBullet particle system

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#66]
Modifying the "Size over time" or toggling the "Looping" mode off in this prefab's particle system causes the bullets to malfunction and then irreversibly stop spawning at all. Fix is to delete the project and then clone again from the repository.

When "Looping" is toggled off the game will spawn super bullets that never get destroyed and create a resource leak which causes the framerate to drop rapidly. After enabling it again, the aforementioned bug happens where the bullets no longer spawn at all. 

These may be bugs related to the beta build but for now it's documented here.

**Comment by alkaitagi** [comment]
Fixed
