### ISSUE TITLE
Ricochet bullet property

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#68]
Add a property for projectiles that allows them to bounce off of walls and/or enemy units and structures (two separate options).

The angle of reflection should depend on both the direction of travel and the angle of the colliding surface.

The number of reflections should also be definable, i.e. if set to 2 then the third surface collision will not reflect but destroy.

**Comment by perfecthumaninterface** [comment]
I think this property should be enabled/disabled within the launcher, and then passed to the projectile when created. Since it's possible we use the same projectiles for different enemies for example, it would be easier than creating unique projectiles for each that only have this one difference.

**Comment by alkaitagi** [comment]
Please see *ProjectileRework* branch where the feature is implemented through *ProjectileBounce* component.

**Comment by perfecthumaninterface** [comment]
I've noticed the projectiles sometimes stick to units rather than bouncing. Tested with the "Bounce Bombs" weapon added on key 4.

**Comment by alkaitagi** [comment]
I believe this happens because creeps are moving, so when projectile bounces for the first time, it is being immediately hit by the creep's move, so it bounces again, effectively eliminating the first bounce. And so it loops. I will need to do a little bit of linear algebra for this.

**Comment by perfecthumaninterface** [comment]
I have also observed this happening on stationary turrets though. And I expect that the case you've described could only happen if the projectile speed is less than the unit speed (I don't believe that's the case here but that's something else to investigate and account for too). 

I'm not sure how related but I also observed that I could get the bullets (specifically of bounce bombs) to shoot inside walls sometimes if I was close enough.

**Comment by alkaitagi** [comment]
If this happens to stationary turrets as well, then it is definitely not the case I described. I will need to do more tests to identify the problem.

**Comment by alkaitagi** [comment]
I could not reproduce the issue with static turrets. Assuming my previous guess was correct, I've implemented directional check for bouncing modifier. The problem seems to be fixed.

**Comment by perfecthumaninterface** [comment]
As far as I can tell it seems to work correctly now.
