### ISSUE TITLE
Burst fire properties for launchers

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#71]
Launchers should have properties for "burst fire," that is, the number of times projectiles are emitted in a burst (one after the other, not simultaneously).

Property values should include:
-Number of times bullets are fired in the burst
-Time between each firing within the burst

The wording is confusing because we have to account for weapons that shoot more than one bullet simultaneously, but it is simple.

If a weapon has a burst value of 3, when the player or unit fires the weapon once it will shoot three times in succession. That is one "burst."

If a weapon has a burst value of 1 then it will emit projectiles once every time it's fired, as we have now.

If a weapon has a burst value of 2 but emits 5 projectiles per shot (e.g. spread launcher), then it will shoot 5 projectiles 2 times, for a total of 10 projectiles in the burst. 

This can be useful for making certain enemy and player weapon behaviors a little more interesting.

**Comment by alkaitagi** [comment]
Implemented

**Comment by perfecthumaninterface** [comment]
It may be worth adding a parameter to set whether the weapon keeps firing after cooldown when you hold the button down or whether you have to click every time you want to fire. Effectively the difference between automatic and semi-automating firing. Maybe call it "Auto."

**Comment by alkaitagi** [comment]
Added *Automatic* property to *BaseLauncher*.

**Comment by perfecthumaninterface** [comment]
Looks good thanks.
