### ISSUE TITLE
Creep AI stops chasing after player death

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#72]
Newly spawned creeps seem to lose all hope after (I believe) the player dies and respawns. 

I suppose that if their chase target is destroyed they should be assigned a new one?

**Comment by alkaitagi** [comment]
Now Creeps always target Player if no destination given and no enemies in the range.

**Comment by perfecthumaninterface** [comment]
Sounds good. We'll need to get further into the game before we can get into AI any deeper.
