### ISSUE TITLE
Bug when core destroyed

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#73]
When the core is destroyed during preview mode there is an error about a particle system and bullets get stuck and frames start to drop.

This does not appear to happen using build and run.

**Comment by alkaitagi** [comment]
I can no longer see that issue. Probably got addressed alongside the other bugs that have been fixed recently.

**Comment by perfecthumaninterface** [comment]
Seems OK to me as well.
