### ISSUE TITLE
Projectile destroy visual effect does not differentiate between collision and time out

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#77]
Currently whenever a projectile is destroyed it plays a destroy effect (particle system). However, it does not differentiate between whether it's being destroyed from collision with a surface/unit or if it's destroyed from exceeding its range/timer. 

My thought is that the effects played should be "on collision" instead of "on destroy."

**Comment by perfecthumaninterface** [comment]
I noticed that with the bouncing projectiles (the tri-shot), there's a particle effect both on collision with bounce surfaces and on destroy. 

I could imagine doing separate effects for both (non-destructive, in this case) collisions and on destroy, but I think at this point it might be excessive (creating so many particle systems). 

As I mentioned above, I think if we simply spawn particles on (any) collision that will be good for now.

**Comment by alkaitagi** [comment]
![image](https://user-images.githubusercontent.com/32439229/69900097-a4368700-1380-11ea-8955-a8e05c61c5de.png)

**Comment by alkaitagi** [comment]
![image](https://user-images.githubusercontent.com/32439229/69900171-4b1b2300-1381-11ea-8236-6886013cab9a.png)

**Comment by alkaitagi** [comment]
The particle spawn effects are controller per projectile modifier. So here you can remove the **OnDestroy** spawn callback and bullet will just disappear on timeout without any effect.
![image](https://user-images.githubusercontent.com/32439229/69900193-7dc51b80-1381-11ea-8fbb-9167464991e6.png)

**Comment by perfecthumaninterface** [comment]
I see, so On Hit does not trigger On Destroy?

**Comment by alkaitagi** [comment]
Not necessarily, unless you explicitly specify that.

**Comment by perfecthumaninterface** [comment]
I found this bug https://github.com/alkaitagi/ProjectBurst/issues/82 while investigating this. I suspect it may effect this issue, so please look into that first.

I can see that with the On Destroy behavior disabled it doesn't trigger particles when the bullet times out, and with the On Hit behavior disabled the bullet doesn't trigger particles when it bounces. I'm curious though what happens when the bullet hits an enemy without bouncing. I suspect that it would (or should?) trigger both On Hit and On Destroy in that case.

**Comment by alkaitagi** [comment]
If you have bounce modifier which has _bounceOffUnits_ set to false then it will not invoke onHit when colliding with unit. Damage, however, will. Each modifier works independently.

**Comment by perfecthumaninterface** [comment]
Alright, so as I understand it now, you can create the particle effect for On Destroy, On Hit for bounce component, or On Hit for damage component. I think this covers all the bases for whatever we need to do.
