### ISSUE TITLE
Projectile stick script timer variable

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#78]
Currently when you add a projectile stick component you need to input the values for the timer adjustments in the On Hit behavior manually. This seems like it could be replaced with an exposed variable (i.e. "Stick Time") that would be easier to work with.  Let me know if I'm wrong.

**Comment by alkaitagi** [comment]
Sure, that shortcut will speed up the design.

**Comment by alkaitagi** [comment]
![image](https://user-images.githubusercontent.com/32439229/69040649-30e75980-09ff-11ea-967f-476e22cd7c28.png)
