### ISSUE TITLE
Projectile speed curve timing

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#79]
The speed over time curve in the projectile component seems to work, but I don't know what the timing of the horizontal axis is (i.e. when does it reach value 1.0?).

This seems like it should be scaled to match the range of the projectile (which is now the "Timer" value as I understand it). I don't believe it is so currently.

**Comment by perfecthumaninterface** [comment]
I believe this is in fact working correctly and scaled to Timer. I've just remembered the editor bug where the first time you click "play" sometimes doesn't include recent changes and that may have thrown me off.

**Comment by alkaitagi** [comment]
Its worth noting that the curve time is normalized: 1 means not 1 second but the end of projectile's timer.

However, curve's value is not, so be careful with that.
