### ISSUE TITLE
Enemy shot (bullet) style

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#8]
For now we will stick with one basic enemy shot or bullet style.

The shot will move in a straight line and constant speed. Direction depends on the enemy and its behavior.

The shot should not be too small, and should not be too fast. A circular shape is good.

Visually the shot should be high-contrast. It should also draw on top of most everything. We should never not be able to clearly see a shot. A light color with a thick dark outline is a good design. 

The hitbox of the shot should be smaller than the entire sprite. It should be good if the inner part of the shot graphic (inside of the outline) corresponds to the hitbox.

The shot is destroyed on collision with any solid object. If it is a player-owned structure, the damage value of the shot is dealt to it. The shot is not destroyed on collision with the player, but player takes damage from the collision.

(drawing to be added)

**Comment by perfecthumaninterface** [comment]
![image](https://user-images.githubusercontent.com/35180513/56483843-511b5e00-649a-11e9-8ab6-61d8954f973c.png)

Something like this is what I'm imagining. I know it appears visually similar to the enemies and such right now but I think the enemy sprites should be changed in the future anyways.

**Comment by alkaitagi** [comment]
Added CircleBullet prefab with this style.
