### ISSUE TITLE
Projectile bounce component "pierces" enemies and walls when set to not bounce off them

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#82]
As per the title, bullets with the Projectile Bounce component seem to go straight through enemies and/or walls when set to not bounce off them, rather than hitting and disappearing. This also has the side effect of causing massive damage to enemies as the bullet collides with the enemy over and over.

**Comment by alkaitagi** [comment]
This is intended behavior because the component must be set to bounce either from units or walls, otherwise why would you place that component? If you want "standard" bullet behavior, that is when it disappears when hitting unit or wall, set bounce modifier to bounce from both walls and units and set bounce count to 0.

**Comment by perfecthumaninterface** [comment]
The issue is when you want one or the other and not both. For instance, if you want the bullet to bounce off walls but not enemies.

**Comment by alkaitagi** [comment]
In that case put Destroy callback on damage modifier.
________________________________

**Comment by alkaitagi** [comment]
And if you want your bullet to go through units while bouncing off walls, add damage, add bounce with _units_ off and _walls_ on, and add pierce with numeric value 0 (so it is infinite).

**Comment by perfecthumaninterface** [comment]
I see. What about if you want the bullet to bounce off units but not walls? This doesn't seem like something I would have wanted to do but the parameter (to not bounce off walls) is there.

**Comment by alkaitagi** [comment]
For that you would need to put 3 modifiers: damage, bounce (and set only _bounceOffUnits_ as true), stick (and set _stickToWalls_ as true and put _Destroy_ on _onHit_ callback).

**Comment by perfecthumaninterface** [comment]
Haha, this is getting convoluted, but that's fine. Originally I expected it to just work simply toggling the booleans but these extra steps are fine as long as it works.

**Comment by alkaitagi** [comment]
> I see. What about if you want the bullet to bounce off units but not walls? This doesn't seem like something I would have wanted to do but the parameter (to not bounce off walls) is there.

I understand. Now projectile has two new callbacks: _onWallEnter_ and _onEnemyEnter_ (invoked before any modifiers). With this addition, the above behavior can be achieved with _damage_ and _bounce_ modifiers with projectile's _onWallEnter_ calling _destroy_.
