### ISSUE TITLE
Building placement doesn't show red over invalid build areas

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#83]
When going to place a building in build mode, the ghost attached to the cursor no longer shows red to indicate an invalid position for placing the building.

![image](https://user-images.githubusercontent.com/35180513/71612177-95ecae00-2b6c-11ea-93f1-04d8d1b7bcd7.png)

**Comment by alkaitagi** [comment]
Strange, it is working for me. Please, check again if you are on "Tether" branch.

![image](https://user-images.githubusercontent.com/32439229/71613772-44b6db80-2bb9-11ea-99de-bc2ecc20db91.png)

**Comment by alkaitagi** [comment]
Fixed. I did not sync BuildManager from Combattest scene.

**Comment by perfecthumaninterface** [comment]
Could we remove the transition time between colors, so it's instantaneous? It's a small thing but we should be careful about prioritizing visual flair over clear information.

**Comment by alkaitagi** [comment]
Removed.

**Comment by perfecthumaninterface** [comment]
Nice thank you.
