### ISSUE TITLE
Build menu transition time

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#85]
I'd like to adjust the time for transitions within the build mode (showing and hiding it etc.) to be a bit shorter. I looked around the project a bit but couldn't find a way to do so.

**Comment by alkaitagi** [comment]
Fixed (from 0.1 to 0.05)

![image](https://user-images.githubusercontent.com/32439229/71656852-20403800-2d4e-11ea-8d6a-6ae3e01ca7c4.png)

**Comment by perfecthumaninterface** [comment]
Thanks! It seems that the transition of the build range ring is separate; is there a value to adjust that? Also, does the "transition out" time of the build menu get added to the "transition in" of the build range ring or do they happen at the same time?

**Comment by alkaitagi** [comment]
The ring animation is controlled by the _Animator_ component, so the values are modifier in the animation window. Both UI and gameobjecs (rings) animations start at the same time and are independent in their durations.

![image](https://user-images.githubusercontent.com/32439229/71764846-4278b800-2efe-11ea-9aa8-619a098fc126.png)

**Comment by perfecthumaninterface** [comment]
I see, I had to search a bit for that window but I found it. I think you've changed it already so it looks good now.
