### ISSUE TITLE
Building spawns in center of map

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#86]
There is a bug that incorrectly spawns a building at this location on the map if it's not occupied:

![image](https://user-images.githubusercontent.com/35180513/71768080-f408f080-2ee0-11ea-9850-c46b92864605.png)

**Steps to recreate:**
1. Open build menu
2. Select a building
3. Close build menu
4. Left-click

**Comment by alkaitagi** [comment]
Fixed.
